modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
issueTrackerURL="https://github.com/Arcomit/acceleratedslashblade/issues"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
credits="Furia, 0999312, Arcomit, AbbyQAQ"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/acceleratedslashblade"
logoFile="slashblade_acceleratedrendering.png"
description = '''
让旧版本（低于1.8.57）重锋兼容加速渲染。
高于这个版本你仍然可以添加该模组，但功能并不会生效:P
Make older versions (below 1.8.57) compatible with accelerated rendering for SlashBlade：Resharped.
You can still add the mod above this version, but the functionality will not work :P
'''

#拔刀剑：重锋(前置)
[[dependencies."${mod_id}"]]
modId = "slashblade"
mandatory = true
versionRange = "[0.1.4,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
